---
name: 'pipeline-components-xmllint'
description: 'XML Lint by Pipeline Components'
author: 'Robbert Müller <spam.me@grols.ch>'
branding:
  icon: 'flag'
  color: 'green'
inputs:
  directory:
    description: 'Directory to lint'
    required: false
    default: '**/*.xml'
  options:
    description: 'Additional options'
    required: false
    default: '--noout'
runs:
  using: 'docker'
  image: docker://pipelinecomponents/xmllint
  args:
    - xmllint
    - '${{ inputs.options }}'
    - '${{ inputs.directory }}'
